dep:
    pnpm install

clean:
    rm -f pnpm-lock.yaml
    pnpm clean

dev *args: dep
    go tool dsh-web-desktopify dev . {{ args }}

bundle *args:
    go tool dsh-web-desktopify bundle . {{ args }}

plugin *args:
    go tool dsh-web-desktopify plugin {{ args }}
